# Generated by Django 2.0.10 on 2019-01-12 21:06

from django.db import migrations, models
import go_back.validators


class Migration(migrations.Migration):

    dependencies = [
        ('go_back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date_expires',
            field=models.DateTimeField(blank=True, null=True, validators=[go_back.validators.valid_date], verbose_name='Go Link Expiry Date'),
        ),
    ]
