# Generated by Django 2.0.5 on 2018-05-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.SlugField(allow_unicode=True, max_length=20, unique=True),
        ),
    ]
