# Generated by Django 2.0.5 on 2018-05-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0002_auto_20180523_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
