# Generated by Django 2.0.5 on 2018-06-03 23:40

from django.db import migrations, models
import go.models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0003_auto_20180524_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='destination',
            field=models.URLField(default='https://go.gmu.edu', help_text='The URL to be redirected to when visiting the shortlink.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(help_text='The shortcode that acts as the unique go link.', max_length=20, unique=True, validators=[go.models.URL.unique_short_validator, go.models.URL.regex_short_validator]),
        ),
    ]
