# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 21:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0003_auto_20160107_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='organization',
            field=models.CharField(default=datetime.datetime(2016, 3, 15, 21, 23, 13, 628051, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
