# Generated by Django 2.0.5 on 2018-06-09 00:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import go.validators


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0004_auto_20180608_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Blocked Status'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Signup Description'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='organization',
            field=models.CharField(default='', max_length=100, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Registration Status'),
        ),
        migrations.AlterField(
            model_name='url',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 9, 0, 25, 38, 606587, tzinfo=utc), verbose_name='Go Link Creation Date'),
        ),
        migrations.AlterField(
            model_name='url',
            name='date_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Go Link Expiry Date'),
        ),
        migrations.AlterField(
            model_name='url',
            name='destination',
            field=models.URLField(default='https://go.gmu.edu', max_length=1000, verbose_name='Go Link Destination URL'),
        ),
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(max_length=20, unique=True, validators=[go.validators.unique_short_validator, go.validators.regex_short_validator], verbose_name='Go Shortcode'),
        ),
    ]
