# Generated by Django 2.0.5 on 2018-06-09 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0006_auto_20180609_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Go Link Creation Date'),
        ),
    ]
